---
- name: Install Portworx ({{ px_image }})
  docker_container:
    name: portworx-install
    image: "{{ px_image }}"
    volumes:
    - "/opt/pwx:/opt/pwx"
    - "/etc/pwx:/etc/pwx"
    auto_remove: yes
    privileged: yes
  become: yes
- command: "/opt/pwx/bin/px-runc install {{ kvdb }} {{ cluster_id }} {{ data_if }} {{ mgmt_if }} {{ device_args }} {{ storageless }} {{ force }} {{ journal_dev }} {{ scheduler }} {{ pxenviron }}"
  become: yes
- service:
  name: portworx
  enabled: yes
  use: service
  become: yes
